#!/bin/bash

set -xu

LIBCUDF_CUFILE_POLICY="OFF" python -u cudf_benchmark.py

for LIBCUDF_CUFILE_THREAD_COUNT in 4 8 16 32 64; do
  LIBCUDF_CUFILE_POLICY="GDS" LIBCUDF_CUFILE_SLICE_SIZE=1048576 LIBCUDF_CUFILE_THREAD_COUNT=${LIBCUDF_CUFILE_THREAD_COUNT} python -u cudf_benchmark.py
done
